name: Fetch PACT Entities

on:
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Fetch data using Python
        run: python3 data_fetcher.py

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: pact-json
          path: output.json

  process-using-ontorefine:
    runs-on: ubuntu-latest
    container:
      image: ontotext/refine:1.2.1
      options: --user root
      ports:
        - 7333:7333
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install requirements
        run: apk update && apk add curl util-linux jq python3

      - name: Run OntoRefine server
        run: /opt/ontorefine/dist/bin/ontorefine &

      - name: Wait for server
        run: |
          for i in $(seq 1 30); do
            curl -sf http://localhost:7333 && break || sleep 5
          done

      - name: Download JSON artifact
        uses: actions/download-artifact@v4
        with:
          name: pact-json
          path: .


      - name: Transform to RDF
        run: |
          mkdir -p outputs
          /opt/ontorefine/dist/bin/ontorefine-cli transform data.json \
            -u http://localhost:7333 \
            --configurations ontorefine-config.json \
            -f json > outputs/pact-entities.ttl

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pact-ttl
          path: outputs/

  commit-and-push:
    runs-on: ubuntu-latest
    needs: process-using-ontorefine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: pact-ttl
          path: outputs/

      - name: Commit and push
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git pull origin ${{ github.ref_name }}
          git add outputs/
          git diff --staged --quiet || git commit -m "Update PACT entities"
          git push origin ${{ github.ref_name }}

  artsdata-push:
    runs-on: ubuntu-latest
    needs: commit-and-push
    steps:
      - name: Push to Artsdata
        uses: culturecreates/artsdata-pipeline-action@v3
        with:
          artifact: pact-organizations
          publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
          downloadUrl: https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/outputs/pact-entities.ttl